server:
  contextPath: /ms-jira
  port: ${port:8989}

jira:
  projects: RECON,HMS,HMSMS,PDS,YYDS,PLUGIN
  developers: huangaoxin,ouyangbo,zengqinggui,hanchonglin,zhengxiang,huangyibo,zhangyizhi,zhudiyang,gongjunqing,zhuminghao,wangbingfu
  testers: zhangchen_dev,zhangling,liufanghua
  testProjects: FJZLTEST

spring:
  mvc:
    async:
      request-timeout: 60000