server:
  contextPath: /ms-jira
  port: ${port:8989}

jira:
  projects: IOTBEDSIDE
#  developers: weixiaokang
  developers: zhoushuyan,huangaoxin,ouyangbo,zengqinggui,zhengxiang,zhangyizhi,gongjunqing,wangbingfu,weixiaokang,luozheng
  developersAndroid:
  developersBackend:
  testers: wufei,zhangling,liufanghua,wujinpeng,zhouxinhui,qiupeiteng,hexueqin,chengjie
  testersJD:
  testProjects: IOTBEDSIDE

spring:
  mvc:
    async:
      request-timeout: 1200000