server:
  contextPath: /ms-jira
  port: ${port:8989}

jira:
  projects: IOTBEDSIDE
#  developers: weixiaokang
  developers: zhoushuyan,huangaoxin,ouyangbo,zengqinggui,zhengxiang,zhangyizhi,gongjunqing,wangbingfu,weixiaokang,luozheng
  developersAndroid: luying,shibing,pengchenwei,douyeliang,ruanyitai,mashoujun,jinsheng,zhangjin,wangzhonghao,wangdapeng
  developersBackend: huminghu,liangfei,lijiaren,wangpengfei,caizhongheng,taoyemeng,fengyan,xufeiyang,zhuwenjie,caihong
  testers: wufei,zhangling,liufanghua,wujinpeng,zhouxinhui,qiupeiteng,hexueqin,chengjie
  testersJD:
  testProjects: IOTBEDSIDE

spring:
  mvc:
    async:
      request-timeout: 1200000