server:
  contextPath: /ms-jira
  port: ${port:8989}

jira:
  projects: RECON,HMS,HMSMS,PDS,YYDS,PLUGIN
  #developers: weixiaokang
  developers: zhoushuyan,huangaoxin,ouyangbo,zengqinggui,hanchonglin,zhengxiang,huangyibo,zhangyizhi,zhudiyang,gongjunqing,zhuminghao,wangbingfu,weixiaokang,wuqingqing,duxin,pandongdong,wangjing,huanghao
  testers: zhangchen_dev,wufei,zhangling,liufanghua
  testProjects: FJZLTEST

spring:
  mvc:
    async:
      request-timeout: 1200000